spring.application.name=sustainability-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/sustainability
spring.datasource.username=postgres
spring.datasource.password=tragedy
spring.jpa.hibernate.ddl-auto=update
